//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 26.11.2020 22:58:43
namespace Model
{
    
    /// <summary>
    /// There are no comments for Entities in the schema.
    /// </summary>
    public partial class Entities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Entities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Note> Notes
        {
            get
            {
                if ((this._Notes == null))
                {
                    this._Notes = base.CreateQuery<Note>("Notes");
                }
                return this._Notes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Note> _Notes;
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Student> Students
        {
            get
            {
                if ((this._Students == null))
                {
                    this._Students = base.CreateQuery<Student>("Students");
                }
                return this._Students;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Student> _Students;
        /// <summary>
        /// There are no comments for Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNotes(Note note)
        {
            base.AddObject("Notes", note);
        }
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"Model\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><EntityTy" +
                "pe Name=\"Note\"><Key><PropertyRef Name=\"noteId\" /></Key><Property Name=\"noteId\" T" +
                "ype=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"h" +
                "ttp://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"subj\" " +
                "Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"t" +
                "rue\" /><Property Name=\"note1\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name" +
                "=\"studentId\" Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationProperty Name=\"Stude" +
                "nt\" Relationship=\"Model.FK_Note_Student\" ToRole=\"Student\" FromRole=\"Note\" /></En" +
                "tityType><EntityType Name=\"Student\"><Key><PropertyRef Name=\"studentId\" /></Key><" +
                "Property Name=\"studentId\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPat" +
                "tern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotatio" +
                "n\" /><Property Name=\"name\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" Fix" +
                "edLength=\"false\" Unicode=\"false\" /><NavigationProperty Name=\"Notes\" Relationship" +
                "=\"Model.FK_Note_Student\" ToRole=\"Note\" FromRole=\"Student\" /></EntityType><Associ" +
                "ation Name=\"FK_Note_Student\"><End Type=\"Model.Student\" Role=\"Student\" Multiplici" +
                "ty=\"1\" /><End Type=\"Model.Note\" Role=\"Note\" Multiplicity=\"*\" /><ReferentialConst" +
                "raint><Principal Role=\"Student\"><PropertyRef Name=\"studentId\" /></Principal><Dep" +
                "endent Role=\"Note\"><PropertyRef Name=\"studentId\" /></Dependent></ReferentialCons" +
                "traint></Association></Schema><Schema Namespace=\"lab_6.Models\" xmlns=\"http://sch" +
                "emas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"Entities\" m:IsDefault" +
                "EntityContainer=\"true\"><EntitySet Name=\"Notes\" EntityType=\"Model.Note\" /><Entity" +
                "Set Name=\"Students\" EntityType=\"Model.Student\" /><AssociationSet Name=\"FK_Note_S" +
                "tudent\" Association=\"Model.FK_Note_Student\"><End Role=\"Note\" EntitySet=\"Notes\" /" +
                "><End Role=\"Student\" EntitySet=\"Students\" /></AssociationSet></EntityContainer><" +
                "/Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for Model.Note in the schema.
    /// </summary>
    /// <KeyProperties>
    /// noteId
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("noteId")]
    public partial class Note
    {
        /// <summary>
        /// Create a new Note object.
        /// </summary>
        /// <param name="noteId">Initial value of noteId.</param>
        /// <param name="subj">Initial value of subj.</param>
        /// <param name="note1">Initial value of note1.</param>
        /// <param name="studentId">Initial value of studentId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Note CreateNote(int noteId, string subj, int note1, int studentId)
        {
            Note note = new Note();
            note.noteId = noteId;
            note.subj = subj;
            note.note1 = note1;
            note.studentId = studentId;
            return note;
        }
        /// <summary>
        /// There are no comments for Property noteId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int noteId
        {
            get
            {
                return this._noteId;
            }
            set
            {
                this.OnnoteIdChanging(value);
                this._noteId = value;
                this.OnnoteIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _noteId;
        partial void OnnoteIdChanging(int value);
        partial void OnnoteIdChanged();
        /// <summary>
        /// There are no comments for Property subj in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string subj
        {
            get
            {
                return this._subj;
            }
            set
            {
                this.OnsubjChanging(value);
                this._subj = value;
                this.OnsubjChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _subj;
        partial void OnsubjChanging(string value);
        partial void OnsubjChanged();
        /// <summary>
        /// There are no comments for Property note1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int note1
        {
            get
            {
                return this._note1;
            }
            set
            {
                this.Onnote1Changing(value);
                this._note1 = value;
                this.Onnote1Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _note1;
        partial void Onnote1Changing(int value);
        partial void Onnote1Changed();
        /// <summary>
        /// There are no comments for Property studentId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int studentId
        {
            get
            {
                return this._studentId;
            }
            set
            {
                this.OnstudentIdChanging(value);
                this._studentId = value;
                this.OnstudentIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _studentId;
        partial void OnstudentIdChanging(int value);
        partial void OnstudentIdChanged();
        /// <summary>
        /// There are no comments for Student in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Student Student
        {
            get
            {
                return this._Student;
            }
            set
            {
                this._Student = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Student _Student;
    }
    /// <summary>
    /// There are no comments for Model.Student in the schema.
    /// </summary>
    /// <KeyProperties>
    /// studentId
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("studentId")]
    public partial class Student
    {
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="studentId">Initial value of studentId.</param>
        /// <param name="name">Initial value of name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Student CreateStudent(int studentId, string name)
        {
            Student student = new Student();
            student.studentId = studentId;
            student.name = name;
            return student;
        }
        /// <summary>
        /// There are no comments for Property studentId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int studentId
        {
            get
            {
                return this._studentId;
            }
            set
            {
                this.OnstudentIdChanging(value);
                this._studentId = value;
                this.OnstudentIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _studentId;
        partial void OnstudentIdChanging(int value);
        partial void OnstudentIdChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Note> Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                if ((value != null))
                {
                    this._Notes = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Note> _Notes = new global::System.Collections.ObjectModel.Collection<Note>();
    }
}
