//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.INotesFeed")]
    public interface INotesFeed {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesFeed/GetNotes", ReplyAction="http://tempuri.org/INotesFeed/GetNotesResponse")]
        System.ServiceModel.Syndication.SyndicationFeedFormatter GetNotes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesFeed/GetNotes", ReplyAction="http://tempuri.org/INotesFeed/GetNotesResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Syndication.SyndicationFeedFormatter> GetNotesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotesFeedChannel : Client.ServiceReference.INotesFeed, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotesFeedClient : System.ServiceModel.ClientBase<Client.ServiceReference.INotesFeed>, Client.ServiceReference.INotesFeed {
        
        public NotesFeedClient() {
        }
        
        public NotesFeedClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotesFeedClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotesFeedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotesFeedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ServiceModel.Syndication.SyndicationFeedFormatter GetNotes() {
            return base.Channel.GetNotes();
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Syndication.SyndicationFeedFormatter> GetNotesAsync() {
            return base.Channel.GetNotesAsync();
        }
    }
}
